// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DownAndInOptionPricer
double DownAndInOptionPricer(double Expiration, double K, double S0, double sigma, double r, double barrier, int num_sims);
RcppExport SEXP _DownAndInOptionPricer_DownAndInOptionPricer(SEXP ExpirationSEXP, SEXP KSEXP, SEXP S0SEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP barrierSEXP, SEXP num_simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Expiration(ExpirationSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type barrier(barrierSEXP);
    Rcpp::traits::input_parameter< int >::type num_sims(num_simsSEXP);
    rcpp_result_gen = Rcpp::wrap(DownAndInOptionPricer(Expiration, K, S0, sigma, r, barrier, num_sims));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DownAndInOptionPricer_DownAndInOptionPricer", (DL_FUNC) &_DownAndInOptionPricer_DownAndInOptionPricer, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_DownAndInOptionPricer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
