# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DownAndInOptionPricer <- function(Expiration, K, S0, sigma, r, barrier, num_sims) {
    .Call(`_DownAndInOptionPricer_DownAndInOptionPricer`, Expiration, K, S0, sigma, r, barrier, num_sims)
}

